"""Application constants shared across the codebase."""

PRIVILEGED_INVENTORY_TIMEOUT_SECONDS = 15
INVENTORY_CACHE_TTL_SECONDS = 30
PREFLIGHT_DEBOUNCE_MS = 200
EVENT_POLL_INTERVAL_MS = 16
FILE_CHUNK_SIZE = 1024 * 1024
DRIVE_SANITIZE_TIMEOUT_SECONDS = 7200
